language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
script:
  - ./gradlew jacocoTestReport --stacktrace
  - ./gradlew sonarqube 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  on:
    branch: master
