language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew jacocoTestReport --stacktrace
  - ./gradlew sonarqube 

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI"
  - git push -q https://$GITHUB_TOKEN@github.com/mboisnard/Rocket --tags

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/libs/*
  on:
    branch: master
